### ISSUE TITLE
Facing the error while launching the traininng launch file

### ISSUE THREAD

**Issue by Avi241** [kuwabaray/ros_rl_for_slam#5]
Hello I am facing this error when I launch the 
```
roslaunch simulate_robot_rl simulate_robot.launch
```
This is the error 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/dqn_for_slam-0.0.1-py3.6.egg/dqn_for_slam/rl_worker.py", line 43, in <module>
    env = gym.make(ENV_NAME)
  File "/home/arvind/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/arvind/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/arvind/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/home/arvind/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/dqn_for_slam-0.0.1-py3.6.egg/dqn_for_slam/environment/robot_rl_env.py", line 12, in <module>
    import tf2_ros
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)
INFO:rospy.core:signal_shutdown [atexit]
[agent-8] process has died [pid 11655, exit code 1, cmd /home/arvind/rl_ws/src/ros_rl_for_slam/simulate_robot_rl/scripts/run_agent.sh __name:=agent __log:=/home/arvind/.ros/log/5512831c-aaf1-11ec-9899-283a4d5b8bff/agent-8.log].
log file: /home/arvind/.ros/log/5512831c-aaf1-11ec-9899-283a4d5b8bff/agent-8*.log
```

Please help me to solve this

**Comment by Avi241** [comment]
Solved
